services:
  database:
    image: mysql:8
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - ./database-data:/var/lib/mysql
    networks:
      - brewery_platform

networks:
  brewery_platform:
