openapi: 3.0.0
paths:
  /device-types:
    get:
      operationId: get
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceTypeResponseDto"
      tags:
        - device-types
  /device-types/test:
    get:
      operationId: test
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - device-types
  /displays:
    get:
      operationId: get
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - displays
  /users/login:
    post:
      operationId: login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginDto"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserLoginResponseDto"
        "201":
          description: ""
      tags:
        - users
info:
  title: Over The Air Brew Brewing Platform
  description: ""
  version: dev
  contact: {}
tags: []
servers: []
components:
  schemas:
    StringPropertyOutput:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        required:
          type: boolean
        placeholder:
          type: string
      required:
        - name
        - type
        - required
        - placeholder
    NumberPropertyOutput:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        required:
          type: boolean
        defaultValue:
          type: number
      required:
        - name
        - type
        - required
        - defaultValue
    SelectBoxPropertyOutput:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        required:
          type: boolean
        values:
          type: array
          items:
            type: string
        defaultValue:
          type: string
      required:
        - name
        - type
        - required
        - values
        - defaultValue
    DeviceTypeResponseDto:
      type: object
      properties:
        name:
          type: string
        properties:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/StringPropertyOutput"
              - $ref: "#/components/schemas/NumberPropertyOutput"
              - $ref: "#/components/schemas/SelectBoxPropertyOutput"
      required:
        - name
        - properties
    UserLoginDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    UserLoginResponseDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        image:
          type: string
          nullable: true
        token:
          type: string
        emailHash:
          type: string
      required:
        - id
        - name
        - email
        - image
        - token
        - emailHash
