/* tslint:disable */
/* eslint-disable */
/**
 * Over The Air Brew Brewing Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StringPropertyOutput
 */
export interface StringPropertyOutput {
    /**
     * 
     * @type {string}
     * @memberof StringPropertyOutput
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof StringPropertyOutput
     */
    'type': string;
    /**
     * 
     * @type {boolean}
     * @memberof StringPropertyOutput
     */
    'required': boolean;
    /**
     * 
     * @type {string}
     * @memberof StringPropertyOutput
     */
    'placeholder': string;
}

