/* tslint:disable */
/* eslint-disable */
/**
 * Over The Air Brew Brewing Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserLoginResponseDto
 */
export interface UserLoginResponseDto {
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponseDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponseDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponseDto
     */
    'image': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponseDto
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponseDto
     */
    'emailHash': string;
}

