services:
  custompios:
    # image: guysoft/custompios:devel
    build:
      context: ../../CustomPiOS/src
      dockerfile: Dockerfile
    pull_policy: always
    container_name: piimage-build
    platform: linux/arm64
    tty: true
    restart: always
    privileged: true
    environment:
      - USER=root
      - BASE_BOARD=raspberrypiarm64
      - DIST_PATH=/distro2
    volumes:
      - ./src:/distro2
      - ../../CustomPiOS/src:/CustomPiOS
    devices:
      - /dev/loop-control
