/* tslint:disable */
/* eslint-disable */
/**
 * Over The Air Brew Brewing Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { NumberPropertyOutput } from './number-property-output';
// May contain unused imports in some cases
// @ts-ignore
import { SelectBoxPropertyOutput } from './select-box-property-output';
// May contain unused imports in some cases
// @ts-ignore
import { StringPropertyOutput } from './string-property-output';

/**
 * @type DeviceTypeResponseDtoPropertiesInner
 * @export
 */
export type DeviceTypeResponseDtoPropertiesInner =
  | NumberPropertyOutput
  | SelectBoxPropertyOutput
  | StringPropertyOutput;
