/* tslint:disable */
/* eslint-disable */
/**
 * Over The Air Brew Brewing Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SelectBoxPropertyOutput
 */
export interface SelectBoxPropertyOutput {
  /**
   *
   * @type {string}
   * @memberof SelectBoxPropertyOutput
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof SelectBoxPropertyOutput
   */
  type: string;
  /**
   *
   * @type {boolean}
   * @memberof SelectBoxPropertyOutput
   */
  required: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof SelectBoxPropertyOutput
   */
  values: Array<string>;
  /**
   *
   * @type {string}
   * @memberof SelectBoxPropertyOutput
   */
  defaultValue: string;
}
