/* tslint:disable */
/* eslint-disable */
/**
 * Over The Air Brew Brewing Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserLoginDto
 */
export interface UserLoginDto {
  /**
   *
   * @type {string}
   * @memberof UserLoginDto
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserLoginDto
   */
  password: string;
}
