#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

if [ "$BREW_PLATFORM_HYPERPIXEL_2_ENABLED" == "yes" ]
then
  apt-get install -y git

  ### setup hyperpixel
  git clone https://github.com/pimoroni/hyperpixel2r.git
  cd ./hyperpixel2r
  sudo ./install.sh

  sed -i '/^[^#]/ s/\(^.*dtoverlay=vc4-kms-v3d.*$\)/#\ \1/' "/${BASE_BOOT_MOUNT_PATH}/config.txt"

  if [ "$BREW_PLATFORM_HYPERPIXEL_2_TOUCH_ENABLED" == "no" ]
  then
    sed -i 's/dtoverlay=hyperpixel2r/dtoverlay=hyperpixel2r:disable-touch/g' "/${BASE_BOOT_MOUNT_PATH}/config.txt"
  fi
fi