name: Build Image

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - pi-image/*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: guysoft/custompios:devel
      options: --privileged
      env:
        USER: root
        BASE_BOARD: raspberrypiarm64
        DIST_PATH: ${{ github.workspace }}/pi-image/src
    strategy:
      matrix:
        variant:
          - hyperpixel2r
    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pi-image
      - name: Build image
        run: |
          cp -f ./custom-config/common.sh /CustomPiOS/common.sh
          cp -f ./custom-config/custompios_nightly_build /CustomPiOS/nightly_build_scripts/custompios_nightly_build

          build --download ${{ matrix.variant }}
