name: Build Image

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - piimage/*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: guysoft/custompios:devel
      options: --privileged
      env:
        USER: root
        BASE_BOARD: raspberrypiarm64
    strategy:
      matrix:
        variant:
          - hyperpixel2r
    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: piimage
      - name: Build image
        working-directory: piimage
        run: |
          mkdir -p /distro
          build --download ${{ matrix.variant }}
