name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PNPM_VERSION: 9.7.0
  MYSQL_ROOT_PASSWORD: testrootpassword
  MYSQL_DATABASE: testdb

jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-and-test.yml
    secrets: inherit
