name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        appName:
          - backend
          - front-end
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install Turbo
        run: npm i -g turbo
      - name: Prune application
        run: pnpm run prune @overtheairbrew/${{ matrix.appName }}
      - name: Install dependencies
        working-directory: out
        run: pnpm install --frozen-lockfile
      - name: Build Application
        working-directory: out
        run: pnpm run build
      - name: Lint Application and Dependencies
        working-directory: out
        run: pnpm run lint

