name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        appName:
          - backend
          - frontend
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate api-client
        run: pnpm run 
      - name: Build Application
        run: pnpm run build --filter=...@overtheairbrew/${{ matrix.appName }}
      - name: Lint Application and Dependencies
        run: pnpm run lint

