name: Push docker images

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'

jobs:
  build-docker-image:
    strategy:
      matrix:
        app:
          - name: backend
            image: overtheairbrew/brewery-platform-backend
    uses: ./.github/workflows/reusable-docker-build-release.yml
    with:
      appName: ${{ matrix.app.name }}
      dockerImageName: ${{ matrix.app.image }}
    secrets: inherit
